package edu.wm.cs.cs301.s2026.wordle.model;

import static org.junit.jupiter.api.Assertions.*;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Supplemental tests for WordleModel. Generated by Claude. Specifically asked to focus on tests that were not covered in WordleModelTestManual.java
 * Focuses on areas not covered (or lightly covered) by WordleModelTestManual:
 *   - Foreground colour on typed vs. evaluated cells
 *   - YELLOW colour logic with multiple positions / repeated letters
 *   - Grid state persistence across multiple submitted rows
 *   - setCurrentRow() column-reset confirmed on every submission, not just first
 *   - Unplayed rows remain null after partial play
 *   - initialize() resets the target word (new game word selected)
 *   - Typing a letter stores the correct character in the grid cell
 *   - Backspace on the very last column (column 4) clears correctly
 *   - setCurrentRow() clears the guess buffer (typing after submit starts fresh)
 *   - Multiple YELLOW letters in the same guess
 *   - Letter present in target at multiple positions — correct position wins GREEN
 *   - getCurrentRow() content (letter identity, not just colour)
 */
public class WordleModelTestGenerated {

    private Model model;

    @BeforeEach
    public void setUp() {
        model = new WordleModel();
        List<String> words = new ArrayList<>();
        words.add("slate");
        words.add("SQQQS");
        words.add("AQAAA");
        words.add("AQQQS");
        words.add("ETQQQ");
        words.add("SSQQQ");
        words.add("telas");
        words.add("QQQQQ");
        model.setWordList(words);
        model.initialize();
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private void typeWords(String word) {
        for (char c : word.toCharArray()) {
            model.setCurrentColumn(c);
        }
    }

    private void setupWithWord(String word) {
        List<String> words = new ArrayList<>();
        words.add(word);
        model.setWordList(words);
        model.initialize();
    }
    private void setupWithWordList(List<String> words) {
        model.setWordList(words);
        model.initialize();
    }

    // ── Foreground colour ────────────────────────────────────────────────────

    @Test
    @DisplayName("Typed (unsubmitted) cell has BLACK foreground")
    public void testTypedCellHasBlackForeground() {
        model.setCurrentColumn('S');
        assertEquals(Color.BLACK, model.getWordleGrid()[0][0].getForegroundColor(),
                "Unsubmitted cell foreground should be BLACK");
    }

    @Test
    @DisplayName("Evaluated cell has WHITE foreground after submission")
    public void testEvaluatedCellHasWhiteForeground() {
        typeWords("SLATE");
        model.setCurrentRow();
        WordleResponse[] row = model.getCurrentRow();
        for (int i = 0; i < row.length; i++) {
            assertEquals(Color.WHITE, row[i].getForegroundColor(),
                    "Submitted cell " + i + " foreground should be WHITE");
        }
    }

    // ── Letter identity in grid cells ────────────────────────────────────────

    @Test
    @DisplayName("Typing three letters populates exactly those three cells (not null), rest stay null")
    public void testTypedLettersCellsPopulated() {
        model.setCurrentColumn('S');
        model.setCurrentColumn('L');
        model.setCurrentColumn('A');

        WordleResponse[][] grid = model.getWordleGrid();
        // Typed cells should be non-null
        assertNotNull(grid[0][0], "Column 0 should be populated after typing 'S'");
        assertNotNull(grid[0][1], "Column 1 should be populated after typing 'L'");
        assertNotNull(grid[0][2], "Column 2 should be populated after typing 'A'");
        // Remaining cells should still be null
        assertNull(grid[0][3], "Column 3 should still be null");
        assertNull(grid[0][4], "Column 4 should still be null");
    }

    @Test
    @DisplayName("Submitted cells are all non-null and have WHITE foreground (letter was retained)")
    public void testSubmittedCellsAllNonNull() {
        typeWords("SLATE");
        model.setCurrentRow();
        WordleResponse[] row = model.getCurrentRow();
        for (int i = 0; i < row.length; i++) {
            assertNotNull(row[i], "Cell " + i + " should not be null after submission");
            // WHITE foreground is only set during evaluation, confirming each cell went through setCurrentRow()
            assertEquals(Color.WHITE, row[i].getForegroundColor(),
                    "Cell " + i + " should have WHITE foreground after evaluation");
        }
    }

    // ── YELLOW colour logic ──────────────────────────────────────────────────

    @Test
    @DisplayName("Multiple YELLOW letters in a single guess")
    public void testMultipleYellowLetters() {
        // Target: SLATE  Guess: ETQQQ  → E is at pos 4 in target (wrong here at 0) = YELLOW,
        //                               T is at pos 3 in target (wrong here at 1) = YELLOW
    	model.setCurrentWord("slate");
        typeWords("ETQQQ");
        model.setCurrentRow();
        WordleResponse[] row = model.getCurrentRow();
        assertEquals(AppColors.YELLOW, row[0].getBackgroundColor(),
                "E should be YELLOW (in SLATE but wrong position)");
        assertEquals(AppColors.YELLOW, row[1].getBackgroundColor(),
                "T should be YELLOW (in SLATE but wrong position)");
        assertEquals(AppColors.GRAY,   row[2].getBackgroundColor(), "Q should be GRAY");
        assertEquals(AppColors.GRAY,   row[3].getBackgroundColor(), "Q should be GRAY");
        assertEquals(AppColors.GRAY,   row[4].getBackgroundColor(), "Q should be GRAY");
    }
    //TODO There is missing logic within the contains() method in the WordleModel class. It fails to consider this scenario.
    @Test
    @DisplayName("Letter at correct position is GREEN even though it also appears elsewhere in target")
    public void testCorrectPositionBeatsYellow() {
        // Target: SLATE  — 'S' only appears at index 0
        // Guess:  SQQQS  — first S is GREEN; last S at index 4 is not in target at any other pos → GRAY
    	model.setCurrentWord("slate");
        typeWords("SQQQS");
        model.setCurrentRow();
        WordleResponse[] row = model.getCurrentRow();
        assertEquals(AppColors.GREEN, row[0].getBackgroundColor(),
                "S at correct position 0 should be GREEN");
        assertEquals(AppColors.GRAY,  row[4].getBackgroundColor(),
                "S at wrong position 4 — no second S in target — should be GRAY");
    }

    @Test
    @DisplayName("Letter in target that appears at a different column is YELLOW")
    public void testLetterInTargetAtDifferentColumnIsYellow() {
        // Target: SLATE  Guess: AQQQS → A exists in SLATE at index 2, not index 0 → YELLOW
    	model.setCurrentWord("slate");
        typeWords("AQQQS");
        model.setCurrentRow();
        WordleResponse[] row = model.getCurrentRow();
        assertEquals(AppColors.YELLOW, row[0].getBackgroundColor(),
                "A at index 0 should be YELLOW (A is in SLATE at index 2)");
    }

    @Test
    @DisplayName("All five letters in word but every position wrong — all YELLOW")
    public void testAllLettersWrongPositionAllYellow() {
        // Target: SLATE  Rearranged so every letter is present but none in place: TELAS
    	model.setCurrentWord("SLATE");
        typeWords("TELAS");
        model.setCurrentRow();
        WordleResponse[] row = model.getCurrentRow();
        for (int i = 0; i < row.length; i++) {
            assertNotEquals(AppColors.GRAY, row[i].getBackgroundColor(),
                    "Cell " + i + " should not be GRAY — letter exists in SLATE");
        }
    }

    // ── Grid persistence across rows ─────────────────────────────────────────

    @Test
    @DisplayName("Previous row cells are not overwritten when a new guess is submitted")
    public void testPreviousRowRetainedAfterSecondSubmission() {
    	model.setCurrentWord("slate");
        typeWords("QQQQQ");
        model.setCurrentRow();               // row 0 = all GRAY

        typeWords("SLATE");
        model.setCurrentRow();               // row 1 = all GREEN

        WordleResponse[][] grid = model.getWordleGrid();
        // Row 0 should still be all GRAY
        for (int col = 0; col < 5; col++) {
            assertEquals(AppColors.GRAY, grid[0][col].getBackgroundColor(),
                    "Row 0 should still be GRAY after a second submission");
        }
        // Row 1 should be all GREEN
        for (int col = 0; col < 5; col++) {
            assertEquals(AppColors.GREEN, grid[1][col].getBackgroundColor(),
                    "Row 1 should be GREEN");
        }
    }

    @Test
    @DisplayName("Rows beyond the current guess remain null during play")
    public void testFutureRowsRemainNullDuringPlay() {
        typeWords("QQQQQ");
        model.setCurrentRow();               // only row 0 is filled

        WordleResponse[][] grid = model.getWordleGrid();
        for (int row = 1; row < grid.length; row++) {
            for (int col = 0; col < grid[row].length; col++) {
                assertNull(grid[row][col],
                        "Cell [" + row + "][" + col + "] should still be null");
            }
        }
    }

    // ── setCurrentRow() column reset across multiple rows ────────────────────

    @Test
    @DisplayName("currentColumn resets to -1 after every submission, not just the first")
    public void testColumnResetsToMinusOneAfterEachSubmission() {
        for (int attempt = 0; attempt < 3; attempt++) {
            typeWords("QQQQQ");
            model.setCurrentRow();
            assertEquals(-1, model.getCurrentColumn(),
                    "currentColumn should be -1 after submission " + (attempt + 1));
        }
    }

    @Test
    @DisplayName("Typing after submission writes into the next row, not the previous one")
    public void testTypingAfterSubmissionWritesIntoNextRow() {
        typeWords("QQQQQ");
        model.setCurrentRow();               // row 0 submitted — all cells WHITE bg

        model.setCurrentColumn('X');         // should go into row 1, column 0
        WordleResponse[][] grid = model.getWordleGrid();

        // Row 1 col 0 should now be populated (non-null) with an unsubmitted WHITE background
        assertNotNull(grid[1][0], "New letter should appear in row 1 col 0");
        assertEquals(Color.WHITE, grid[1][0].getBackgroundColor(),
                "Newly typed cell in row 1 should have WHITE (unsubmitted) background");

        // Row 1 columns 1-4 should still be null — only one letter was typed
        for (int col = 1; col < 5; col++) {
            assertNull(grid[1][col], "Row 1 col " + col + " should still be null");
        }
    }

    // ── Backspace edge cases ─────────────────────────────────────────────────

    @Test
    @DisplayName("Backspace on the last column (col 4) clears that cell")
    public void testBackspaceOnLastColumn() {
        typeWords("SLATE");                  // currentColumn = 4
        model.backspace();
        assertNull(model.getWordleGrid()[0][4],
                "Column 4 should be null after backspace");
        assertEquals(3, model.getCurrentColumn(),
                "currentColumn should decrement to 3");
    }

    @Test
    @DisplayName("Backspace then retype replaces cell content — cell is non-null with WHITE background")
    public void testBackspaceThenRetypeUpdatesCell() {
        model.setCurrentColumn('S');
        model.setCurrentColumn('Q');         // col 1 = Q (non-null)
        model.backspace();                   // erase Q — col 1 back to null
        assertNull(model.getWordleGrid()[0][1],
                "Column 1 should be null after backspace");

        model.setCurrentColumn('L');         // col 1 = L (non-null again)
        assertNotNull(model.getWordleGrid()[0][1],
                "Column 1 should be non-null after retyping");
        assertEquals(Color.WHITE, model.getWordleGrid()[0][1].getBackgroundColor(),
                "Retyped cell should have WHITE (unsubmitted) background");
    }

    // ── initialize() resets the target word ──────────────────────────────────

    @Test
    @DisplayName("initialize() with a new word list picks the new target word")
    public void testInitializeChangesTargetWord() {
        // First target is SLATE
    	setupWithWord("slate");
        assertEquals("SLATE", model.getCurrentWord());

        setupWithWord("crane");

        assertEquals("CRANE", model.getCurrentWord(),
                "After re-initializing with a new word list, target word should update");
    }

    @Test
    @DisplayName("initialize() clears any partially typed letters from the grid")
    public void testInitializeClearsPartialInput() {
        typeWords("SLA");                    // partial input
        model.initialize();                  // reset

        WordleResponse[][] grid = model.getWordleGrid();
        for (int col = 0; col < 3; col++) {
            assertNull(grid[0][col],
                    "Column " + col + " should be null after initialize()");
        }
    }

    // ── getCurrentRowNumber() at boundaries ──────────────────────────────────

    @Test
    @DisplayName("getCurrentRowNumber() returns 4 after five submissions")
    public void testCurrentRowNumberAfterFiveSubmissions() {
        for (int i = 0; i < 5; i++) {
            typeWords("QQQQQ");
            model.setCurrentRow();
        }
        assertEquals(4, model.getCurrentRowNumber(),
                "After 5 submissions getCurrentRowNumber() should return 4");
    }

    @Test
    @DisplayName("getCurrentRowNumber() returns 5 after six submissions (game over)")
    public void testCurrentRowNumberAfterSixSubmissions() {
        for (int i = 0; i < 6; i++) {
            typeWords("QQQQQ");
            model.setCurrentRow();
        }
        assertEquals(5, model.getCurrentRowNumber(),
                "After 6 submissions getCurrentRowNumber() should return 5");
    }

    // ── Repeated letters in target / guess interaction ────────────────────────

    @Test
    @DisplayName("Repeated letter in guess: one matches (GREEN), duplicate is GRAY")
    public void testRepeatedLetterInGuessOneGreenOneDray() {
        // Target: AAAAB  Guess: AQAAA
        // Index 0: A == A → GREEN
        // Index 1: Q not in target → GRAY
        // Index 2: A == A → GREEN
        // Index 3: A == A → GREEN
        // Index 4: A != B but A is in target — however positions 0,2,3 are already exact
        //           contains() checks all positions ≠ current, so index 4 A will find
        //           a match at 0,2,3 in the target → YELLOW
    	List<String> words = new ArrayList<>();
        words.add("aaaab");
        words.add("aqaaa");
        setupWithWordList(words);
        model.setCurrentWord("AAAAB");
        
        typeWords("AQAAA");
        model.setCurrentRow();
        WordleResponse[] row = model.getCurrentRow();

        assertEquals(AppColors.GREEN, row[0].getBackgroundColor(), "Index 0: A → GREEN");
        assertEquals(AppColors.GRAY,  row[1].getBackgroundColor(), "Index 1: Q → GRAY");
        assertEquals(AppColors.GREEN, row[2].getBackgroundColor(), "Index 2: A → GREEN");
        assertEquals(AppColors.GREEN, row[3].getBackgroundColor(), "Index 3: A → GREEN");
        // Index 4: A is not at position 4 in target (B is), but A exists at other positions → YELLOW
        assertEquals(AppColors.YELLOW, row[4].getBackgroundColor(), "Index 4: A → YELLOW");
    }

    @Test
    @DisplayName("Letter appears once in target but twice in guess — second occurrence is GRAY")
    public void testLetterTwiceInGuessOnceInTarget() {
        // Target: SQQQQ  Guess: SSQQQ
        // Index 0: S == S → GREEN
        // Index 1: S != Q, and S exists elsewhere in target only at index 0 (index 0 ≠ 1) → YELLOW
        //   (contains() finds S at index 0, which != column 1, so returns true → YELLOW)
    	List<String> words = new ArrayList<>();
        words.add("sqqqq");
        words.add("ssqqq");
        setupWithWordList(words);
        model.setCurrentWord("SQQQQ");

        typeWords("SSQQQ");
        model.setCurrentRow();
        WordleResponse[] row = model.getCurrentRow();

        assertEquals(AppColors.GREEN, row[0].getBackgroundColor(),
                "Index 0: S exact match → GREEN");
        assertEquals(AppColors.GRAY, row[1].getBackgroundColor(),
                "Index 1: second S — S already used by GREEN at index 0 → GRAY");
        assertEquals(AppColors.GREEN, row[2].getBackgroundColor(),
                "Index 2: Q exact match → GREEN");
    }


}